services:
  - type: web
    name: btc-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd hackaton && npm install
    startCommand: bash start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
